linters-settings:
  funlen:
    lines: 100
    statements: 50
  nestif:
    min-complexity: 10
  cyclop:
    max-complexity: 20

linters:
  enable-all: true
  disable:
    # deprecated linters
    - golint
    - interfacer
    - scopelint
    - maligned

    # suppress type assertion warnings since we assert the same we passed
    - forcetypeassert
    # all struct has omitempty, so all fields in struct are not required
    - exhaustivestruct
    # disable gofumpt since it has conflict with wsl(white space letter) linter
    - gofumpt
    # integration tests need to done in sequential manner
    - paralleltest
    # need to allow single character variable name
    - varnamelen
    # return the error need not to wrap
    - wrapcheck
    # default value needs to be provided as integer literal
    - gomnd

    - gochecknoglobals
    - bodyclose
    - lll # should reduce line length or configure max length of line
    - noctx
    - gochecknoinits

    # need to remove once sdk version is released
    - gomoddirectives

  fast: false
